/* Generate dist/_headers (Cloudflare Pages) with a strict Content-Security-Policy.
 *
 * The only executable inline scripts are ours (the index boot gate, which must be
 * inline to set the view before first paint, and demo.html's token resolver), so
 * script-src runs inline code by sha256 HASH rather than 'unsafe-inline' — an
 * injected <script> can't execute. The hashes are computed here from the actual
 * file bytes, so the policy can never drift from the markup: change a boot script
 * and its hash changes on the next build. style-src keeps 'unsafe-inline' because
 * buildCSS() injects a <style> whose contents are dynamic and can't be hashed;
 * that's a stylesheet, not a script vector.
 *
 * Run from build.sh AFTER every HTML transform, so it hashes the deployed bytes.
 * Exports are pure so the smoke suite can guard the policy's shape. */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

// script types the browser actually executes (everything else — application/
// ld+json, importmap, speculationrules — is data and never runs, so CSP doesn't
// gate it and it must NOT be hashed)
const EXEC_TYPES = new Set(['', 'text/javascript', 'application/javascript', 'module']);

// The exact inner text of every executable inline <script> — that's the byte
// range the browser hashes for a CSP script hash. An HTML parser ends a script at
// the first "</script>", so the inner text can never itself contain that literal;
// the non-greedy match is therefore exact.
export function inlineScriptHashes(html) {
  const out = [];
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(html))) {
    const attrs = m[1];
    if (/\bsrc\s*=/i.test(attrs)) continue;                 // external → allowlisted by origin, not hashed
    const type = (attrs.match(/\btype\s*=\s*["']?([^"'\s>]*)/i)?.[1] || '').toLowerCase();
    if (!EXEC_TYPES.has(type)) continue;                    // non-JS block (e.g. JSON-LD) → not executed
    out.push("'sha256-" + createHash('sha256').update(m[2], 'utf8').digest('base64') + "'");
  }
  return out;
}

export function cspFrom(scriptHashes) {
  const hashes = [...new Set(scriptHashes)].join(' ');
  return [
    "default-src 'self'",
    "base-uri 'self'",
    "object-src 'none'",
    "frame-ancestors 'self'",
    "form-action 'self'",
    "img-src 'self' data:",
    "font-src 'self'",
    "style-src 'self' 'unsafe-inline'",                     // dynamic buildCSS <style> — can't be hashed
    `script-src 'self' ${hashes} https://static.cloudflareinsights.com`.replace(/\s+/g, ' '),
    "connect-src 'self' https://cloudflareinsights.com",    // Cloudflare Web Analytics beacon RUM POST
    "upgrade-insecure-requests",
  ].join('; ');
}

export function headersText(csp) {
  return `# Generated by scripts/gen-headers.mjs — do not edit by hand.
# Applies to every path served by Cloudflare Pages.
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
`;
}

// CLI: hash the inline scripts across every dist/*.html and write dist/_headers.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const dir = process.argv[2] || 'dist';
  const files = readdirSync(dir).filter(f => f.endsWith('.html'));
  const hashes = files.flatMap(f => inlineScriptHashes(readFileSync(`${dir}/${f}`, 'utf8')));
  writeFileSync(`${dir}/_headers`, headersText(cspFrom(hashes)));
  console.log(`wrote ${dir}/_headers (${new Set(hashes).size} inline-script hash(es) across ${files.length} pages)`);
}
